"""fix

Revision ID: 9c73d6dde0b7
Revises: d1741353d7ed
Create Date: 2024-08-14 23:33:28.559598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c73d6dde0b7'
down_revision = 'd1741353d7ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_list_enemies', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_class', schema=None) as batch_op:
        batch_op.drop_column('current_list_enemies')

    # ### end Alembic commands ###
