"""added stats_points

Revision ID: 0acab64dc943
Revises: b7dcf43731c3
Create Date: 2024-09-24 16:46:11.855506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0acab64dc943'
down_revision = 'b7dcf43731c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stats_points', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_class', schema=None) as batch_op:
        batch_op.drop_column('stats_points')

    # ### end Alembic commands ###
