"""users table

Revision ID: 3108edef3927
Revises: 
Create Date: 2024-08-06 15:53:18.634656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3108edef3927'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=12), nullable=False),
    sa.Column('description', sa.String(length=30), nullable=True),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('character_created', sa.DateTime(), nullable=False),
    sa.Column('stats_STR', sa.Integer(), nullable=False),
    sa.Column('stats_AGI', sa.Integer(), nullable=False),
    sa.Column('stats_INT', sa.Integer(), nullable=False),
    sa.Column('stats_CON', sa.Integer(), nullable=False),
    sa.Column('stats_WIS', sa.Integer(), nullable=False),
    sa.Column('physical_attack', sa.Integer(), nullable=False),
    sa.Column('magical_attack', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('physical_defense', sa.Integer(), nullable=False),
    sa.Column('magical_defense', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('current_hp', sa.Integer(), nullable=False),
    sa.Column('exp_rate', sa.Integer(), nullable=False),
    sa.Column('critical_chance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('character_class', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_class_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_class', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_class_name'))

    op.drop_table('character_class')
    # ### end Alembic commands ###
