"""current zone encounter

Revision ID: 5bf1b1cc171f
Revises: beb45b597bea
Create Date: 2024-08-06 18:56:38.070643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bf1b1cc171f'
down_revision = 'beb45b597bea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_zone_encounter', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_class', schema=None) as batch_op:
        batch_op.drop_column('current_zone_encounter')

    # ### end Alembic commands ###
