"""fix

Revision ID: b7dcf43731c3
Revises: 9c73d6dde0b7
Create Date: 2024-08-20 00:40:15.477770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'b7dcf43731c3'
down_revision = '9c73d6dde0b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_class', schema=None) as batch_op:
        batch_op.drop_column('current_list_enemies')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_list_enemies', sqlite.JSON(), nullable=False))

    # ### end Alembic commands ###
