"""current exp

Revision ID: d1741353d7ed
Revises: 5bf1b1cc171f
Create Date: 2024-08-06 19:14:01.580092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1741353d7ed'
down_revision = '5bf1b1cc171f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_exp', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_class', schema=None) as batch_op:
        batch_op.drop_column('current_exp')

    # ### end Alembic commands ###
